version: "2"
checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  tslint:
    enabled: true
    config: static/tslint.json
  fixme:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.ts"
  - "**.js"
  - "**.jsx"
  - "**.go"
  - "**.html"
exclude_paths:
- build/
- db/
- static/node_modules/
- static/build/
- vendor/
