version: "2"
checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
  method-count:
    enabled: false
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
        typescript:
          mass_threshold: 60
        go:
  eslint:
    enabled: true
    config:
      config: static/.eslintrc
  fixme:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
exclude_patterns:
  - "build/"
  - "db/migrations/"
  - "**/node_modules/"
  - "static/www/"
  - "**/*.d.ts"
