version: "2"
checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
  method-count:
    enabled: false
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
        typescript:
          mass_threshold: 60
        go:
  eslint:
    enabled: true
    config:
      config: static/.eslintrc
  fixme:
    enabled: true
  gofmt:
    enabled: false # Doesn't understand generics
  govet:
    enabled: true
ratings:
  paths:
    - "**.css"
    - "**.inc"
    - "**.ts"
    - "**.tsx"
    - "**.js"
    - "**.jsx"
    - "**.go"
    - "**.html"
exclude_paths:
  - build/
  - db/migrations/
  - static/node_modules/
  - static/www/
  - vendor/
  - static/src/components.d.ts
