dist: trusty
sudo: required

notifications:
  email: false

services:
  - docker

language: go

go:
  - 1.8
  
jdk:
  - oraclejdk8
  
cache:
  yarn: true
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.cache/bower'
    
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
      - zip
  sonarcloud:
    organization: "chadweimer-github"
    branches:
      - master
    token:
      secure: "2f8c445efa94f8f0fee778207f0cabcee8a6c992"

install:
  # Put this here temporarily so it happens before npm and bower
  # components are installed. Better way would be in test/build, with file exclusions.
  - sonar-scanner
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make install

script:
  make build docker
  # test image
  #- docker run cwmr/gomp:latest ???

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker push cwmr/gomp:latest
      docker push cwmr/gomp:armhf
    elif [ -z "$TRAVIS_TAG" ]; then
      docker tag cwmr/gomp:latest cwmr/gomp:dev
      docker tag cwmr/gomp:armhf cwmr/gomp:dev-armhf
      docker push cwmr/gomp:dev
      docker push cwmr/gomp:dev-armhf
    else
      docker tag cwmr/gomp:latest cwmr/gomp:$TRAVIS_TAG
      docker tag cwmr/gomp:armhf cwmr/gomp:$TRAVIS_TAG-armhf
      docker push cwmr/gomp:$TRAVIS_TAG
      docker push cwmr/gomp:$TRAVIS_TAG-armhf
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file:
    - build/*.tar.gz
    - build/*.zip
  skip_cleanup: true
  on:
    tags: true
