FROM balenalib/armv7hf-debian:buster
LABEL maintainer="ch@dweimer.com"

#RUN apk add --no-cache ca-certificates

WORKDIR /var/app/gomp
COPY build/linux/armhf/ ./
VOLUME /var/app/gomp/data

ENV PORT 5000
EXPOSE 5000

ENTRYPOINT ["./gomp"]
