openapi: 3.0.1
info:
  title: GOMP
  version: "1.0"
paths: {}
components:
  schemas:
    accessLevel:
      type: string
      enum:
        - admin
        - editor
        - viewer
      x-go-custom-tag: db:"access_level"
      x-oapi-codegen-extra-tags:
        db: access_level
    recipeState:
      type: string
      enum:
        - active
        - archived
      x-go-custom-tag: db:"current_state"
      x-oapi-codegen-extra-tags:
        db: current_state
    searchField:
      type: string
      enum:
        - name
        - ingredients
        - directions
    sortBy:
      type: string
      enum:
        - name
        - id
        - rating
        - created
        - modified
        - random
      x-go-custom-tag: db:"sort_by"
      x-oapi-codegen-extra-tags:
        db: sort_by
    sortDir:
      type: string
      enum:
        - asc
        - desc
      x-go-custom-tag: db:"sort_dir"
      x-oapi-codegen-extra-tags:
        db: sort_dir
    appInfo:
      type: object
      required:
        - version
      properties:
        version:
          type: string
          readOnly: true
    appConfiguration:
      required:
        - title
      type: object
      properties:
        title:
          type: string
          x-go-custom-tag: db:"title"
          x-oapi-codegen-extra-tags:
            db: title
    note:
      required:
        - text
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          x-go-custom-tag: db:"id"
          x-oapi-codegen-extra-tags:
            db: id
        recipeId:
          type: integer
          format: int64
          readOnly: true
          x-go-custom-tag: db:"recipe_id"
          x-oapi-codegen-extra-tags:
            db: recipe_id
        text:
          minLength: 1
          type: string
          x-go-custom-tag: db:"note"
          x-oapi-codegen-extra-tags:
            db: note
        createdAt:
          type: string
          format: date-time
          readOnly: true
          x-go-custom-tag: db:"created_at"
          x-oapi-codegen-extra-tags:
            db: created_at
          x-go-type: time.Time
        modifiedAt:
          type: string
          format: date-time
          readOnly: true
          x-go-custom-tag: db:"modified_at"
          x-oapi-codegen-extra-tags:
            db: modified_at
          x-go-type: time.Time
    recipeBase:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          x-go-custom-tag: db:"id"
          x-oapi-codegen-extra-tags:
            db: id
        name:
          minLength: 1
          type: string
          x-go-custom-tag: db:"name"
        state:
          $ref: "#/components/schemas/recipeState"
        createdAt:
          type: string
          format: date-time
          readOnly: true
          x-go-custom-tag: db:"created_at"
          x-oapi-codegen-extra-tags:
            db: created_at
          x-go-type: time.Time
        modifiedAt:
          type: string
          format: date-time
          readOnly: true
          x-go-custom-tag: db:"modified_at"
          x-oapi-codegen-extra-tags:
            db: modified_at
          x-go-type: time.Time
    recipe:
      allOf:
        - $ref: "#/components/schemas/recipeBase"
        - type: object
          required:
            - servingSize
            - nutritionInfo
            - ingredients
            - directions
            - storageInstructions
            - sourceUrl
            - time
            - tags
          properties:
            servingSize:
              type: string
              x-go-custom-tag: db:"serving_size"
              x-oapi-codegen-extra-tags:
                db: serving_size
            time:
              type: string
              x-go-custom-tag: db:"recipe_time"
              x-oapi-codegen-extra-tags:
                db: recipe_time
            nutritionInfo:
              type: string
              x-go-custom-tag: db:"nutrition_info"
              x-oapi-codegen-extra-tags:
                db: nutrition_info
            ingredients:
              type: string
              x-go-custom-tag: db:"ingredients"
              x-oapi-codegen-extra-tags:
                db: ingredients
            directions:
              type: string
              x-go-custom-tag: db:"directions"
              x-oapi-codegen-extra-tags:
                db: directions
            storageInstructions:
              type: string
              x-go-custom-tag: db:"storage_instructions"
              x-oapi-codegen-extra-tags:
                db: storage_instructions
            sourceUrl:
              type: string
              x-go-custom-tag: db:"source_url"
              x-oapi-codegen-extra-tags:
                db: source_url
            tags:
              type: array
              items:
                type: string
              x-go-custom-tag: db:"tags"
              x-oapi-codegen-extra-tags:
                db: tags
    recipeCompact:
      allOf:
        - $ref: "#/components/schemas/recipeBase"
        - type: object
          properties:
            thumbnailUrl:
              type: string
              readOnly: true
              x-go-custom-tag: db:"thumbnail_url"
              x-oapi-codegen-extra-tags:
                db: thumbnail_url
            averageRating:
              type: number
              readOnly: true
              x-go-custom-tag: db:"avg_rating"
              x-oapi-codegen-extra-tags:
                db: avg_rating
    recipeImage:
      type: object
      required:
        - recipeId
        - name
        - url
        - thumbnailUrl
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          x-go-custom-tag: db:"id"
          x-oapi-codegen-extra-tags:
            db: id
        recipeId:
          type: integer
          format: int64
          readOnly: true
          x-go-custom-tag: db:"recipe_id"
          x-oapi-codegen-extra-tags:
            db: recipe_id
        name:
          type: string
          readOnly: true
          x-go-custom-tag: db:"name"
          x-oapi-codegen-extra-tags:
            db: name
        url:
          type: string
          readOnly: true
          x-go-custom-tag: db:"url"
          x-oapi-codegen-extra-tags:
            db: url
        thumbnailUrl:
          type: string
          readOnly: true
          x-go-custom-tag: db:"thumbnail_url"
          x-oapi-codegen-extra-tags:
            db: thumbnail_url
        createdAt:
          type: string
          format: date-time
          readOnly: true
          x-go-custom-tag: db:"created_at"
          x-oapi-codegen-extra-tags:
            db: created_at
          x-go-type: time.Time
        modifiedAt:
          type: string
          format: date-time
          readOnly: true
          x-go-custom-tag: db:"modified_at"
          x-oapi-codegen-extra-tags:
            db: modified_at
          x-go-type: time.Time
    searchFilter:
      type: object
      required:
        - query
        - withPictures
        - fields
        - states
        - tags
        - sortBy
        - sortDir
      properties:
        query:
          type: string
          x-go-custom-tag: db:"query"
          x-oapi-codegen-extra-tags:
            db: query
        withPictures:
          type: boolean
          nullable: true
          x-go-custom-tag: db:"with_pictures"
          x-oapi-codegen-extra-tags:
            db: with_pictures
        fields:
          type: array
          items:
            $ref: "#/components/schemas/searchField"
        states:
          type: array
          items:
            $ref: "#/components/schemas/recipeState"
        tags:
          type: array
          items:
            type: string
        sortBy:
          $ref: "#/components/schemas/sortBy"
        sortDir:
          $ref: "#/components/schemas/sortDir"
    savedSearchFilterCompact:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          x-go-custom-tag: db:"id"
          x-oapi-codegen-extra-tags:
            db: id
        userId:
          type: integer
          format: int64
          readOnly: true
          x-go-custom-tag: db:"user_id"
          x-oapi-codegen-extra-tags:
            db: user_id
        name:
          minLength: 1
          type: string
          x-go-custom-tag: db:"name"
          x-oapi-codegen-extra-tags:
            db: name
    savedSearchFilter:
      allOf:
        - $ref: "#/components/schemas/savedSearchFilterCompact"
        - $ref: "#/components/schemas/searchFilter"
    user:
      type: object
      required:
        - username
        - accessLevel
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          x-go-custom-tag: db:"id"
          x-oapi-codegen-extra-tags:
            db: id
        username:
          type: string
          x-go-custom-tag: db:"username"
          x-oapi-codegen-extra-tags:
            db: username
        accessLevel:
          $ref: "#/components/schemas/accessLevel"
        createdAt:
          type: string
          format: date-time
          readOnly: true
          x-go-custom-tag: db:"created_at"
          x-oapi-codegen-extra-tags:
            db: created_at
          x-go-type: time.Time
        modifiedAt:
          type: string
          format: date-time
          readOnly: true
          x-go-custom-tag: db:"modified_at"
          x-oapi-codegen-extra-tags:
            db: modified_at
          x-go-type: time.Time
    userSettings:
      type: object
      required:
        - favoriteTags
      properties:
        userId:
          type: integer
          format: int64
          readOnly: true
          x-go-custom-tag: db:"user_id"
          x-oapi-codegen-extra-tags:
            db: user_id
        homeTitle:
          type: string
          nullable: true
          x-go-custom-tag: db:"home_title"
          x-oapi-codegen-extra-tags:
            db: home_title
        homeImageUrl:
          type: string
          nullable: true
          x-go-custom-tag: db:"home_image_url"
          x-oapi-codegen-extra-tags:
            db: home_image_url
        favoriteTags:
          type: array
          items:
            type: string
          x-go-custom-tag: db:"favorite_tags"
          x-oapi-codegen-extra-tags:
            db: favorite_tags
