ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

# Enable all available rules
enableAllRules = true

# Disabled rules
[rule.add-constant]
Disabled = true
[rule.banned-characters]
Disabled = true
[rule.cognitive-complexity]
Disabled = true
[rule.cyclomatic]
Disabled = true
[rule.file-header]
Disabled = true
[rule.function-length]
Disabled = true
[rule.line-length-limit]
Disabled = true
[rule.max-public-structs]
Disabled = true
[rule.package-comments]
Disabled = true
# [rule.var-naming]
# Disabled = true

# Exclude tests from certain rules
[rule.defer]
Exclude = ["TEST"]
