swagger: "2.0"
info:
  title: GOMP
  version: "1.0"
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /app/info:
    get:
      tags:
        - app
      description: get application info
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/appInfo"
  /app/configuration:
    get:
      tags:
        - app
      description: get application configuration
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/appConfiguration"
    put:
      tags:
        - app
      description: modify application configuration
      parameters:
        - $ref: "#/parameters/appConfigurationInBody"
      responses:
        "204":
          description: No Content
  /recipes:
    get:
      tags:
        - recipes
      description: list the recipes
      security:
        - Bearer: []
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/recipeCompact"
    post:
      tags:
        - recipes
      description: add a recipe
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/recipeInBody"
      responses:
        "201":
          description: Created
  /recipes/{recipeId}:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
    get:
      tags:
        - recipes
      description: get a single recipe
      security:
        - Bearer: []
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/recipe"
    put:
      tags:
        - recipes
      description: modify an existing recipe
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/recipeInBody"
      responses:
        "204":
          description: No Content
    delete:
      tags:
        - recipes
      description: delete an existing recipe
      security:
        - Bearer: []
      responses:
        "204":
          description: No Content
  /recipes/{recipeId}/state:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
    get:
      tags:
        - recipes
      description: get the state of a recipe
      security:
        - Bearer: []
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/recipeState"
    put:
      tags:
        - recipes
      description: modify the state of a recipe
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/recipeStateInBody"
      responses:
        "204":
          description: No Content
  /recipes/{recipeId}/rating:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
    get:
      tags:
        - recipes
      description: get the current rating of a recipe
      security:
        - Bearer: []
      responses:
        "200":
          description: OK
          schema:
            type: integer
    put:
      tags:
        - recipes
      description: modify the rating of a recipe
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/ratingInBody"
      responses:
        "204":
          description: No Content
  /recipes/{recipeId}/image:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
    get:
      tags:
        - images
      description: get the main image of a recipe
      security:
        - Bearer: []
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/recipeImage"
    put:
      tags:
        - images
      description: set the main image of a recipe
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/imageIdInBody"
      responses:
        "204":
          description: No Content
  /recipes/{recipeId}/images:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
    get:
      tags:
        - images
      description: get the images on a recipe
      security:
        - Bearer: []
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/recipeImage"
    post:
      tags:
        - images
      description: add an image to a recipe
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/fileInForm"
      responses:
        "201":
          description: Created
  /recipes/{recipeId}/images/{imageId}:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
      - $ref: "#/parameters/imageIdInPath"
    delete:
      tags:
        - images
      description: delete an existing image from a recipe
      security:
        - Bearer: []
      responses:
        "204":
          description: No Content
  /recipes/{recipeId}/notes:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
    get:
      tags:
        - notes
      description: get the notes on a recipe
      security:
        - Bearer: []
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/note"
    post:
      tags:
        - notes
      description: add a note to a recipe
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/noteInBody"
      responses:
        "201":
          description: Created
  /recipes/{recipeId}/notes/{noteId}:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
      - $ref: "#/parameters/noteIdInPath"
    put:
      tags:
        - notes
      description: modify a note
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/noteInBody"
      responses:
        "204":
          description: No Content
    delete:
      tags:
        - notes
      description: delete an existing note
      security:
        - Bearer: []
      responses:
        "204":
          description: No Content
  /recipes/{recipeId}/links:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
    get:
      tags:
        - links
      description: get the links on a recipe
      security:
        - Bearer: []
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/recipeCompact"
    post:
      tags:
        - links
      description: add a link to a recipe
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/destRecipeIdInBody"
      responses:
        "201":
          description: Created
  /recipes/{recipeId}/links/{destRecipeId}:
    parameters:
      - $ref: "#/parameters/recipeIdInPath"
      - $ref: "#/parameters/destRecipeIdInPath"
    delete:
      tags:
        - links
      description: delete an existing link
      security:
        - Bearer: []
      responses:
        "204":
          description: No Content
  /uploads:
    post:
      tags:
        - app
      summary: Uploads a file
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file_content
          type: file
      responses:
        "201":
          description: Created

parameters:
  recipeIdInPath:
    name: recipeId
    in: path
    type: integer
    format: int64
    required: true
  destRecipeIdInPath:
    name: destRecipeId
    in: path
    type: integer
    format: int64
    required: true
  imageIdInPath:
    name: imageId
    in: path
    type: integer
    required: true
  noteIdInPath:
    name: noteId
    in: path
    type: integer
    required: true
  appConfigurationInBody:
    name: appConfiguration
    in: body
    schema:
      $ref: "#/definitions/appConfiguration"
    required: true
  recipeInBody:
    name: recipe
    in: body
    schema:
      $ref: "#/definitions/recipe"
    required: true
  recipeStateInBody:
    name: state
    in: body
    schema:
      $ref: "#/definitions/recipeState"
    required: true
  destRecipeIdInBody:
    name: destRecipeId
    in: body
    schema:
      type: integer
      format: int64
    required: true
  ratingInBody:
    name: rating
    in: body
    schema:
      type: integer
    required: true
  imageIdInBody:
    name: imageId
    in: body
    schema:
      type: integer
      format: int64
  noteInBody:
    name: recipe
    in: body
    schema:
      $ref: "#/definitions/note"
    required: true
  fileInForm:
    in: formData
    name: file_content
    type: file

definitions:
  appInfo:
    type: object
    required:
      - version
    properties:
      version:
        type: string
        readOnly: true
  appConfiguration:
    type: object
    required:
      - title
    properties:
      title:
        type: string
        x-go-custom-tag: 'db:"title"'
  recipeState:
    type: string
    enum:
      - active
      - archived
      - deleted
  recipeBase:
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        x-go-custom-tag: 'db:"id"'
      name:
        type: string
        minLength: 1
        x-go-custom-tag: 'db:"name"'
      state:
        $ref: "#/definitions/recipeState"
        x-go-custom-tag: 'db:"current_state"'
      createdAt:
        type: string
        format: date-time
        readOnly: true
        x-go-type:
          type: Time
          import:
            package: time
          hints:
            noValidation: true
        x-go-custom-tag: 'db:"created_at"'
      modifiedAt:
        type: string
        format: date-time
        readOnly: true
        x-go-type:
          type: Time
          import:
            package: time
          hints:
            noValidation: true
        x-go-custom-tag: 'db:"modified_at"'
      avgerageRating:
        type: number
        readOnly: true
        x-go-custom-tag: 'db:"avg_rating"'
  recipeCompact:
    allOf:
      - $ref: "#/definitions/recipeBase"
      - type: object
        properties:
          thumbnail_url:
            type: string
            x-go-custom-tag: 'db:"thumbnail_url"'
  recipe:
    allOf:
      - $ref: "#/definitions/recipeBase"
      - type: object
        properties:
          servingSize:
            type: string
            x-go-custom-tag: 'db:"serving_size"'
          nutritionInfo:
            type: string
            x-go-custom-tag: 'db:"nutrition_info"'
          ingredients:
            type: string
            x-go-custom-tag: 'db:"ingredients"'
          directions:
            type: string
            x-go-custom-tag: 'db:"directions"'
          storageInstructions:
            type: string
            x-go-custom-tag: 'db:"storage_instructions"'
          sourceUrl:
            type: string
            x-go-custom-tag: 'db:"source_url"'
          tags:
            type: array
            items:
              type: string
            x-go-custom-tag: 'db:"tags"'
  recipeImage:
    type: object
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        x-go-custom-tag: 'db:"id"'
      recipeId:
        type: integer
        format: int64
        readOnly: true
        x-go-custom-tag: 'db:"recipe_id"'
      name:
        type: string
        x-go-custom-tag: 'db:"name"'
      url:
        type: string
        x-go-custom-tag: 'db:"url"'
      thumbnailUrl:
        type: string
        x-go-custom-tag: 'db:"thumbnail_url"'
      createdAt:
        type: string
        format: date-time
        readOnly: true
        x-go-type:
          type: Time
          import:
            package: time
          hints:
            noValidation: true
        x-go-custom-tag: 'db:"created_at"'
      modifiedAt:
        type: string
        format: date-time
        readOnly: true
        x-go-type:
          type: Time
          import:
            package: time
          hints:
            noValidation: true
        x-go-custom-tag: 'db:"modified_at"'
  note:
    type: object
    required:
      - recipeId
      - note
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        x-go-custom-tag: 'db:"id"'
      recipeId:
        type: integer
        format: int64
        readOnly: true
        x-go-custom-tag: 'db:"recipe_id"'
      note:
        type: string
        minLength: 1
        x-go-custom-tag: 'db:"note"'
      createdAt:
        type: string
        format: date-time
        readOnly: true
        x-go-type:
          type: Time
          import:
            package: time
          hints:
            noValidation: true
        x-go-custom-tag: 'db:"created_at"'
      modifiedAt:
        type: string
        format: date-time
        readOnly: true
        x-go-type:
          type: Time
          import:
            package: time
          hints:
            noValidation: true
        x-go-custom-tag: 'db:"modified_at"'

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
