swagger: "2.0"
info:
  title: GOMP
  version: "1.0"
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
  /recipes:
    get:
      tags:
        - recipes
      responses:
        200:
          description: list the recipes
          schema:
            type: array
            items:
              $ref: "#/definitions/recipe"
    post:
      tags:
        - recipes
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/recipe"
      responses:
        201:
          description: Created
definitions:
  recipe:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
      ingredients:
        type: string
      directions:
        type: string
      servingSize:
        type: string
