/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PageCreateRecipe {
    }
    interface PageEditRecipe {
    }
    interface PageHome {
    }
    interface PageRecipes {
    }
    interface PageSearch {
    }
    interface PageViewRecipe {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageCreateRecipeElement extends Components.PageCreateRecipe, HTMLStencilElement {
    }
    var HTMLPageCreateRecipeElement: {
        prototype: HTMLPageCreateRecipeElement;
        new (): HTMLPageCreateRecipeElement;
    };
    interface HTMLPageEditRecipeElement extends Components.PageEditRecipe, HTMLStencilElement {
    }
    var HTMLPageEditRecipeElement: {
        prototype: HTMLPageEditRecipeElement;
        new (): HTMLPageEditRecipeElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageRecipesElement extends Components.PageRecipes, HTMLStencilElement {
    }
    var HTMLPageRecipesElement: {
        prototype: HTMLPageRecipesElement;
        new (): HTMLPageRecipesElement;
    };
    interface HTMLPageSearchElement extends Components.PageSearch, HTMLStencilElement {
    }
    var HTMLPageSearchElement: {
        prototype: HTMLPageSearchElement;
        new (): HTMLPageSearchElement;
    };
    interface HTMLPageViewRecipeElement extends Components.PageViewRecipe, HTMLStencilElement {
    }
    var HTMLPageViewRecipeElement: {
        prototype: HTMLPageViewRecipeElement;
        new (): HTMLPageViewRecipeElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-create-recipe": HTMLPageCreateRecipeElement;
        "page-edit-recipe": HTMLPageEditRecipeElement;
        "page-home": HTMLPageHomeElement;
        "page-recipes": HTMLPageRecipesElement;
        "page-search": HTMLPageSearchElement;
        "page-view-recipe": HTMLPageViewRecipeElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PageCreateRecipe {
    }
    interface PageEditRecipe {
    }
    interface PageHome {
    }
    interface PageRecipes {
    }
    interface PageSearch {
    }
    interface PageViewRecipe {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-create-recipe": PageCreateRecipe;
        "page-edit-recipe": PageEditRecipe;
        "page-home": PageHome;
        "page-recipes": PageRecipes;
        "page-search": PageSearch;
        "page-view-recipe": PageViewRecipe;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-create-recipe": LocalJSX.PageCreateRecipe & JSXBase.HTMLAttributes<HTMLPageCreateRecipeElement>;
            "page-edit-recipe": LocalJSX.PageEditRecipe & JSXBase.HTMLAttributes<HTMLPageEditRecipeElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-recipes": LocalJSX.PageRecipes & JSXBase.HTMLAttributes<HTMLPageRecipesElement>;
            "page-search": LocalJSX.PageSearch & JSXBase.HTMLAttributes<HTMLPageSearchElement>;
            "page-view-recipe": LocalJSX.PageViewRecipe & JSXBase.HTMLAttributes<HTMLPageViewRecipeElement>;
        }
    }
}
