version: '2'

volumes:
  data:
  db-data:
services:
  gomp:
    image: cwmr/gomp
    depends_on:
      - gomp-db
    environment:
      - DATABASE_URL=postgres://dbuser:dbpassword@gomp-db/gomp?sslmode=disable
      - GOMP_UPLOAD_PATH=/var/app/gomp/data/uploads
      - SECURE_KEY=UpdateMe
    volumes:
      - data:/var/app/gomp/data
    ports:
      - 5000:5000

  gomp-db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=gomp
    volumes:
      - db-data:/var/lib/postgresql/data
