version: '2'

volumes:
  data:
  db-data:
services:
  web:
    image: ghcr.io/chadweimer/gomp
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://dbuser:dbpassword@db/gomp?sslmode=disable
    volumes:
      - data:/var/app/gomp/data
    ports:
      - 5000:5000
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=gomp
    volumes:
      - db-data:/var/lib/postgresql/data
