/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Note, Recipe, RecipeCompact, User, UserSettings } from "./models";
export namespace Components {
    interface AppRoot {
    }
    interface ImageUploader {
    }
    interface NoteEditor {
        "note": Note | null;
    }
    interface PageAdmin {
    }
    interface PageHome {
        "userSettings": UserSettings | null;
    }
    interface PageLogin {
    }
    interface PageRecipe {
        "activatedCallback": () => Promise<void>;
        "recipeId": number;
    }
    interface PageSearch {
        "activatedCallback": () => Promise<void>;
    }
    interface PageSettings {
    }
    interface RecipeCard {
        "recipe": RecipeCompact | null;
    }
    interface RecipeEditor {
        "recipe": Recipe | null;
    }
    interface SearchFilterEditor {
    }
    interface UserEditor {
        "user": User | null;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLImageUploaderElement extends Components.ImageUploader, HTMLStencilElement {
    }
    var HTMLImageUploaderElement: {
        prototype: HTMLImageUploaderElement;
        new (): HTMLImageUploaderElement;
    };
    interface HTMLNoteEditorElement extends Components.NoteEditor, HTMLStencilElement {
    }
    var HTMLNoteEditorElement: {
        prototype: HTMLNoteEditorElement;
        new (): HTMLNoteEditorElement;
    };
    interface HTMLPageAdminElement extends Components.PageAdmin, HTMLStencilElement {
    }
    var HTMLPageAdminElement: {
        prototype: HTMLPageAdminElement;
        new (): HTMLPageAdminElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageLoginElement extends Components.PageLogin, HTMLStencilElement {
    }
    var HTMLPageLoginElement: {
        prototype: HTMLPageLoginElement;
        new (): HTMLPageLoginElement;
    };
    interface HTMLPageRecipeElement extends Components.PageRecipe, HTMLStencilElement {
    }
    var HTMLPageRecipeElement: {
        prototype: HTMLPageRecipeElement;
        new (): HTMLPageRecipeElement;
    };
    interface HTMLPageSearchElement extends Components.PageSearch, HTMLStencilElement {
    }
    var HTMLPageSearchElement: {
        prototype: HTMLPageSearchElement;
        new (): HTMLPageSearchElement;
    };
    interface HTMLPageSettingsElement extends Components.PageSettings, HTMLStencilElement {
    }
    var HTMLPageSettingsElement: {
        prototype: HTMLPageSettingsElement;
        new (): HTMLPageSettingsElement;
    };
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeEditorElement extends Components.RecipeEditor, HTMLStencilElement {
    }
    var HTMLRecipeEditorElement: {
        prototype: HTMLRecipeEditorElement;
        new (): HTMLRecipeEditorElement;
    };
    interface HTMLSearchFilterEditorElement extends Components.SearchFilterEditor, HTMLStencilElement {
    }
    var HTMLSearchFilterEditorElement: {
        prototype: HTMLSearchFilterEditorElement;
        new (): HTMLSearchFilterEditorElement;
    };
    interface HTMLUserEditorElement extends Components.UserEditor, HTMLStencilElement {
    }
    var HTMLUserEditorElement: {
        prototype: HTMLUserEditorElement;
        new (): HTMLUserEditorElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "image-uploader": HTMLImageUploaderElement;
        "note-editor": HTMLNoteEditorElement;
        "page-admin": HTMLPageAdminElement;
        "page-home": HTMLPageHomeElement;
        "page-login": HTMLPageLoginElement;
        "page-recipe": HTMLPageRecipeElement;
        "page-search": HTMLPageSearchElement;
        "page-settings": HTMLPageSettingsElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-editor": HTMLRecipeEditorElement;
        "search-filter-editor": HTMLSearchFilterEditorElement;
        "user-editor": HTMLUserEditorElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface ImageUploader {
    }
    interface NoteEditor {
        "note"?: Note | null;
    }
    interface PageAdmin {
    }
    interface PageHome {
        "userSettings"?: UserSettings | null;
    }
    interface PageLogin {
    }
    interface PageRecipe {
        "recipeId"?: number;
    }
    interface PageSearch {
    }
    interface PageSettings {
    }
    interface RecipeCard {
        "recipe"?: RecipeCompact | null;
    }
    interface RecipeEditor {
        "recipe"?: Recipe | null;
    }
    interface SearchFilterEditor {
    }
    interface UserEditor {
        "user"?: User | null;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "image-uploader": ImageUploader;
        "note-editor": NoteEditor;
        "page-admin": PageAdmin;
        "page-home": PageHome;
        "page-login": PageLogin;
        "page-recipe": PageRecipe;
        "page-search": PageSearch;
        "page-settings": PageSettings;
        "recipe-card": RecipeCard;
        "recipe-editor": RecipeEditor;
        "search-filter-editor": SearchFilterEditor;
        "user-editor": UserEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "image-uploader": LocalJSX.ImageUploader & JSXBase.HTMLAttributes<HTMLImageUploaderElement>;
            "note-editor": LocalJSX.NoteEditor & JSXBase.HTMLAttributes<HTMLNoteEditorElement>;
            "page-admin": LocalJSX.PageAdmin & JSXBase.HTMLAttributes<HTMLPageAdminElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-login": LocalJSX.PageLogin & JSXBase.HTMLAttributes<HTMLPageLoginElement>;
            "page-recipe": LocalJSX.PageRecipe & JSXBase.HTMLAttributes<HTMLPageRecipeElement>;
            "page-search": LocalJSX.PageSearch & JSXBase.HTMLAttributes<HTMLPageSearchElement>;
            "page-settings": LocalJSX.PageSettings & JSXBase.HTMLAttributes<HTMLPageSettingsElement>;
            "recipe-card": LocalJSX.RecipeCard & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "recipe-editor": LocalJSX.RecipeEditor & JSXBase.HTMLAttributes<HTMLRecipeEditorElement>;
            "search-filter-editor": LocalJSX.SearchFilterEditor & JSXBase.HTMLAttributes<HTMLSearchFilterEditorElement>;
            "user-editor": LocalJSX.UserEditor & JSXBase.HTMLAttributes<HTMLUserEditorElement>;
        }
    }
}
