BEGIN;

ALTER TABLE recipe_note
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN modified_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE recipe_image
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN modified_at SET DEFAULT CURRENT_TIMESTAMP;

COMMIT;
